### ISSUE TITLE
Maybe an incompatibility with Jobs Reborn.

### ISSUE THREAD

**Issue by MrFindus** [catch441/Ultimate_Economy#25] opened 2020-01-13 22:14 UTC
[23:10:02] [Craft Scheduler Thread - 4137/WARN]: [Jobs] Plugin Jobs v4.15.2 generated an exception while executing task 31854

java.lang.IllegalStateException: Asynchronous scoreboard creation!
	at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[patched_1.14.4.jar:git-Paper-230]
	at org.bukkit.craftbukkit.v1_14_R1.scoreboard.CraftScoreboardManager.getNewScoreboard(CraftScoreboardManager.java:44) ~[patched_1.14.4.jar:git-Paper-230]
	at org.bukkit.craftbukkit.v1_14_R1.scoreboard.CraftScoreboardManager.getNewScoreboard(CraftScoreboardManager.java:25) ~[patched_1.14.4.jar:git-Paper-230]
	at com.ue.player.EconomyPlayer.setScoreboard(EconomyPlayer.java:445) ~[?:?]
	at com.ue.player.EconomyPlayer.updateScoreBoard(EconomyPlayer.java:463) ~[?:?]
	at com.ue.player.EconomyPlayer.increasePlayerAmount(EconomyPlayer.java:393) ~[?:?]
	at com.ue.vault.Economy_UltimateEconomy.depositPlayer(Economy_UltimateEconomy.java:33) ~[?:?]
	at com.gamingmesh.jobs.economy.VaultEconomy.depositPlayer(VaultEconomy.java:32) ~[?:?]
	at com.gamingmesh.jobs.tasks.BufferedPaymentTask.run(BufferedPaymentTask.java:41) ~[?:?]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-230]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.14.4.jar:git-Paper-230]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.14.4.jar:git-Paper-230]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_202]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_202]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]

**Comment by catch441** [comment] 2020-01-16 17:38
which ue version? I will check it

**Comment by MrFindus** [comment] 2020-01-16 18:58
I use the 1.2.3

**Comment by catch441** [comment] 2020-02-01 09:19
is maybe already fixed with a BukkitRunnable task, can't reproduce it with version 1.2.4

**Closed as completed by catch441** 2020-02-01 09:19 UTC
Labels: bug
